# Generated by Django 3.0.2 on 2021-03-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Piazza',
            new_name='Tweet',
        ),
    ]
