# Generated by Django 3.0.2 on 2021-03-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0002_auto_20210319_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
